"""Generate the Bus Button property inspector (pi/busbutton.html) from
catalog.EVENT_GROUPS - catalog.py is the source of truth, so new events
show up in the Elgato app's grouped dropdown automatically. Runs from
streamdeck_plugin/build.ps1.
"""
import sys
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "python"))

from thebus_ai_bridge.catalog import EVENT_GROUPS  # noqa: E402

OUT = ROOT / "streamdeck_plugin" / "pi" / "busbutton.html"

TEMPLATE = """<!DOCTYPE html>
<!-- GENERATED by tools/gen_button_pi.py - DO NOT EDIT BY HAND -->
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ background:#2d2d2d; color:#d8d8d8; font:13px "Segoe UI",sans-serif;
         margin:8px; }}
  .row {{ display:flex; align-items:center; margin:6px 0; }}
  .lbl {{ width:90px; color:#969696; }}
  select {{ flex:1; background:#3d3d3d; color:#d8d8d8; border:1px solid #555;
           border-radius:4px; padding:4px; }}
  input[type=checkbox] {{ margin-right:6px; }}
</style>
</head>
<body>
<div class="row">
  <div class="lbl">Event</div>
  <select id="event">
{options}
  </select>
</div>
<div class="row">
  <div class="lbl"></div>
  <label><input type="checkbox" id="hold"> hold while pressed
         (horn, headlight flash)</label>
</div>
<script>
let ws, piUuid;
function send() {{
  ws.send(JSON.stringify({{
    event: "setSettings", context: piUuid,
    payload: {{
      event: document.getElementById("event").value,
      hold: document.getElementById("hold").checked
    }}
  }}));
}}
function connectElgatoStreamDeckSocket(port, uuid, registerEvent, info, actionInfo) {{
  piUuid = uuid;
  const settings = (JSON.parse(actionInfo).payload || {{}}).settings || {{}};
  document.getElementById("event").value = settings.event || "Horn";
  document.getElementById("hold").checked = !!settings.hold;
  ws = new WebSocket("ws://127.0.0.1:" + port);
  ws.onopen = () => ws.send(JSON.stringify({{event: registerEvent, uuid: uuid}}));
  document.getElementById("event").onchange = send;
  document.getElementById("hold").onchange = send;
}}
</script>
</body>
</html>
"""


def main():
    lines = []
    for group, events in EVENT_GROUPS.items():
        lines.append(f'    <optgroup label="{escape(group)}">')
        for name, desc in events.items():
            lines.append(f'      <option value="{escape(name)}">'
                         f'{escape(name)} — {escape(desc)}</option>')
        lines.append("    </optgroup>")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(TEMPLATE.format(options="\n".join(lines)),
                   encoding="utf-8")
    n = sum(len(v) for v in EVENT_GROUPS.values())
    print(f"wrote {OUT} ({n} events in {len(EVENT_GROUPS)} groups)")


if __name__ == "__main__":
    main()
