"""Generate the Feature property inspector (pi/feature.html) from
FEATURE_LABELS - autopilot.py is the source of truth, so new features
show up in the Elgato app's dropdown automatically. Runs from
streamdeck_plugin/build.ps1.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "python"))

from thebus_ai_bridge.autopilot import FEATURE_LABELS  # noqa: E402

OUT = ROOT / "streamdeck_plugin" / "pi" / "feature.html"

TEMPLATE = """<!DOCTYPE html>
<!-- GENERATED by tools/gen_feature_pi.py - DO NOT EDIT BY HAND -->
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ background:#2d2d2d; color:#d8d8d8; font:13px "Segoe UI",sans-serif;
         margin:8px; }}
  .row {{ display:flex; align-items:center; margin:6px 0; }}
  .lbl {{ width:90px; color:#969696; }}
  select {{ flex:1; background:#3d3d3d; color:#d8d8d8; border:1px solid #555;
           border-radius:4px; padding:4px; }}
</style>
</head>
<body>
<div class="row">
  <div class="lbl">Feature</div>
  <select id="feature">
{options}
  </select>
</div>
<script>
let ws, piUuid;
function connectElgatoStreamDeckSocket(port, uuid, registerEvent, info, actionInfo) {{
  piUuid = uuid;
  const sel = document.getElementById("feature");
  const settings = (JSON.parse(actionInfo).payload || {{}}).settings || {{}};
  sel.value = settings.feature || "speed_control";
  ws = new WebSocket("ws://127.0.0.1:" + port);
  ws.onopen = () => ws.send(JSON.stringify({{event: registerEvent, uuid: uuid}}));
  sel.onchange = () => ws.send(JSON.stringify({{
    event: "setSettings", context: piUuid,
    payload: {{feature: sel.value}}
  }}));
}}
</script>
</body>
</html>
"""


def short(label: str) -> str:
    """Dropdown-sized label: cut at ' - ' / ' (' and cap the length."""
    for sep in (" - ", " ("):
        if sep in label:
            label = label.split(sep, 1)[0]
    label = " ".join(label.split())
    return label if len(label) <= 48 else label[:45] + "..."


def main():
    lines = [f'    <option value="{name}">{short(label)}</option>'
             for name, label in FEATURE_LABELS.items()]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(TEMPLATE.format(options="\n".join(lines)),
                   encoding="utf-8")
    print(f"wrote {OUT} ({len(FEATURE_LABELS)} features)")


if __name__ == "__main__":
    main()
